### PR TITLE
fix(pmp): login by gitlab account

### LINKED ISSUE #197: Login by gitlab account

### PR DESCRIPTION
**Pull request by Stefaneek**
closes #197

### CODE REVIEW

File: libs/server/auth/api-rest/src/lib/controllers/auth.controller.ts [hunk 1]
```diff
@@ -11,20 +11,12 @@ export class AuthController {
...
-        return this.authFacade.getGithubAccessToken(body.code);
-      }
-
-      default: {
-        throw new NotImplementedException(
-          `authorization for ${body.platform} is not implemented yet`
-        );
-      }
+    if (body.platform in Platform) {
+      return this.authFacade.getAccessToken(body.code, body.platform);
```
Comment (Sikora00) [inline libs/server/auth/api-rest/src/lib/controllers/auth.controller.ts:15]: Very good improvement

File: libs/server/auth/core/application-services/src/lib/queries/get-access-token.query.ts/get-access-token.handler.ts [hunk 2]
```diff
@@ -8,26 +8,26 @@ import {
...
-    this.authTokenRepository = authTokenRepositoryFactory(Platform.github);
-  }
+  ) {}
 
-  async execute(query: GetGithubAccessTokenQuery): Promise<AuthTokenReadModel> {
-    const { token } = await this.authTokenRepository.getAccessToken(query.githubCode);
-    const userData = { ...(await this.userRepository.loadCurrentUser(token, Platform.github)) };
+  async execute(query: GetAccessTokenQuery): Promise<AuthTokenReadModel> {
+    const { code, platform } = query;
+    this.authTokenRepository = this.authTokenRepositoryFactory(platform);
```
Comment (Sikora00) [inline libs/server/auth/core/application-services/src/lib/queries/get-access-token.query.ts/get-access-token.handler.ts:28]: Great!
