### PR TITLE
fix(pmp-api): 500 on statistics if some bitbucket repository has no pull requests

### LINKED ISSUE #237: 500 on statistics if some repository has no pull requests
**Describe the bug**

**To Reproduce**

1. Add repository which doesn't have any pending pull request.
2. Go to repositories statistics
3. Notice API call with status code 500

**Expected behavior**
we should receive statistics also with this repository.

### PR DESCRIPTION
**Pull request by Artix1500**
closes #237

### CODE REVIEW

File: libs/server/repository/infrastructure/src/lib/bitbucket/mappers/map-bitbucket-repository.ts [hunk 1]
```diff
@@ -8,6 +8,6 @@ export const mapBitbucketRepository = (repo: BitbucketRepositoryEntity) =>
     displayName: repo.name,
     id: BitbucketUuidUtil.parseFrom(repo.uuid),
     name: repo.slug,
-    owner: repo.owner.username,
+    owner: repo.owner.username || repo.owner.nickname || 'Owner Name Not Found',
```
Comment (Sikora00) [inline libs/server/repository/infrastructure/src/lib/bitbucket/mappers/map-bitbucket-repository.ts:11]: throw an exception if we can't find the owner's name because this value is crucial to request the remote API for the repository.

Comment (Artix1500) [reply libs/server/repository/infrastructure/src/lib/bitbucket/mappers/map-bitbucket-repository.ts]: Should be alright now :)

File: libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts [hunk 2]
```diff
@@ -34,7 +34,12 @@ export class BitbucketRepositoryRepository extends RemoteRepositoryRepository {
         headers: { Authorization: `Bearer ${token}` }
       })
       .pipe(
-        map((res: AxiosResponse) => res.data),
+        map((res: AxiosResponse) => {
+          if (!(res.data.username || res.data.nickname)) {
+            throw new Error('No username or nickname provided');
```
Comment (MaciejSikorski) [inline libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts:39]: This must be something more specific than just an error. We need to handle this somehow in ErrorsInterceptor

File: libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts [hunk 3]
```diff
@@ -34,7 +34,12 @@ export class BitbucketRepositoryRepository extends RemoteRepositoryRepository {
         headers: { Authorization: `Bearer ${token}` }
       })
       .pipe(
-        map((res: AxiosResponse) => res.data),
+        map((res: AxiosResponse) => {
+          if (!(res.data.username || res.data.nickname)) {
+            throw { response: { status: 422 } };
```
Comment (Sikora00) [inline libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts:39]: you can just throw the CoreUnprocessableEntityException form this point with some message like "Cannot resolve the owner of the ${fullName}"

Comment (Artix1500) [reply libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts:39]: But then we will get an error in catchRequestExceptions due to lack of object property response.

Comment (MaciejSikorski) [reply libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts:39]: so maybe we should only process an object with instanceof AxiosResponse, or another discriminator there,

File: libs/server/shared/util-exception/src/lib/operators.ts [hunk 4]
```diff
@@ -10,14 +11,19 @@ export function catchRequestExceptions(): OperatorFunction<any, any> {
...
     source$.pipe(
       catchError((err: AxiosError) => {
-        switch (err.response.status) {
-          case 401:
-            return throwError(new CoreUnauthorizedFoundException());
-          case 404:
-            return throwError(new CoreNotFoundException());
-          default:
-            return throwError(err);
+        if ('response' in err) {
```
Comment (Sikora00) [inline libs/server/shared/util-exception/src/lib/operators.ts:14]:
```suggestion
        if (err instanceof AxiosError) {
```
OR
```suggestion
        if (err.response && err.response.status) {
```
