### PR TITLE
fix(pmp-web): fix redirect and single user ui

### LINKED ISSUE #17: Display user statistics
Implement a table with prs of a single user.

### PR DESCRIPTION
**Pull request by Shaelex**
Fixed redirect from users to single user statistics.
Fixed redirect from single user statistics to github pr.
Fixed author display name.

Resolve #17

### CODE REVIEW

File: libs/pmp-web/user/single-user-statistics/feature/src/lib/components/single-user-statistics-table/single-user-statistics-table.component.ts [hunk 1]
```diff
@@ -1,20 +1,18 @@
...
   @Input()
   tableData: PrStatistics[];
 
-  constructor() {}
-
-  ngOnInit(): void {}
-
-  onNavigateToItem(any): void {}
+  onNavigateToItem(url: string): void {
+    window.open(url, '_blank');
```
Comment (MaciejSikorski) [inline libs/pmp-web/user/single-user-statistics/feature/src/lib/components/single-user-statistics-table/single-user-statistics-table.component.ts]: It would be better for type checking if you receive here a single PrStatistics object as an argument.
